name: Build documentation

on:
  push:
    branches:
    - master
    - deploy-to-aws

env:
  AWS_REGION: us-east-1

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: 3r1co/ssc
        tag_with_sha: true
    - uses: minchao/cfn-nag-action@master
      with:
        args: '--input-path cf-all.yaml'
    - name: deploy-to-aws
      if: github.ref == 'refs/heads/master'
      run: |
        aws configure set default.region $AWS_REGION
        aws configure set default.output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        #aws cloudformation deploy --template-file ecs-task.yaml --stack-name eric-stack --no-fail-on-empty-changeset
        aws cloudformation deploy --template-file ecs-task.yaml --stack-name ecs-task --parameter-overrides ImageName=docker.io/3r1co/ssc:sha-$(git rev-parse --short HEAD) --no-fail-on-empty-changeset
        #aws eks update-kubeconfig --name isen
        #kubectl get nodes