name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        registry: docker.io
        repository: 3r1co/ssc
        tags: ${{ GITHUB_SHA }}
