name: Build documentation

on:
  push:
    branches:
    - master
    - deploy-to-aws
    - deploy-to-k8s

env:
  AWS_REGION: us-east-1

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: 3r1co/ssc
        tag_with_sha: true
    - name: use klar
      run: |
        wget -q https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O klar
        chmod +x klar
        CLAIR_OUTPUT=High CLAIR_ADDR=http://clair.3r1.co:6060 ./klar 3r1co/ssc:sha-$(git rev-parse --short HEAD)
    - uses: minchao/cfn-nag-action@master
      with:
        args: '--input-path cf-all.yaml'
    - name: prepare-kustomize
      run: |
        sed -i "s#IMAGE_NAME#3r1co/ssc#g" kustomization.yaml
        sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
        cat kustomization.yaml
    - name: configure-aws
      run: |
        aws configure set default.region $AWS_REGION
        aws configure set default.output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
    - name: deploy-to-k8s
      if: github.ref == 'refs/heads/deploy-to-k8s'
      run: |
        aws eks update-kubeconfig --name isen
        kubectl kustomize . | kubectl apply -f -
    - name: deploy-to-aws
      if: github.ref == 'refs/heads/master'
      run: |
        aws cloudformation deploy --template-file ecs-task.yaml --stack-name ecs-task --parameter-overrides ImageName=docker.io/3r1co/ssc:sha-$(git rev-parse --short HEAD) --no-fail-on-empty-changeset